name: Fetch data from Google Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # co godzinę

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client

      - name: Fetch data from Google Sheets
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: |
          import json
          import gspread
          from oauth2client.service_account import ServiceAccountCredentials

          # Konfiguracja połączenia z API
          credentials_dict = json.loads('${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}')
          creds = ServiceAccountCredentials.from_json_keyfile_dict(
              credentials_dict,
              scopes=["https://www.googleapis.com/auth/spreadsheets"]
          )
          client = gspread.authorize(creds)

          # Odczyt danych z arkusza
          sheet_id = 1qLz321mYARmPy-PmN1dVsYGWY47WLq9MzjAavGhJ7q8
          sheet = client.open_by_key(sheet_id).sheet1
          data = sheet.get_all_records()
          print(data)
